import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    paddingTop: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    flexDirection: 'column',
    rowGap: 40,
  },
  welcomeBox: {
    borderColor: '#e8e8e8',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderRadius: 15,
    justifyContent: 'center',
    width: '75%',
    height: '40%',
    alignItems: 'center',
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    flexWrap: 'wrap',
    rowGap: 30,
  },
  welcomeText: {
    fontSize: 40,
    color: '#333',
    fontWeight: '800',
  },
  welcomeBlurb: {
    fontSize: 25,
    color: '#4C4C4C',
    fontWeight: '300',
    marginRight: 15,
    marginLeft: 15,
    textAlign: 'center',
  },

  viewTutorialText: {
    fontSize: 25,
    color: '#4C4C4C',
    fontWeight: '500',
    textAlign: 'center',

    // paddingLeft: ,
  },
  tutorialBox: {
    borderColor: '#e8e8e8',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderRadius: 15,
    justifyContent: 'center',
    width: '75%',
    height: '40%',
    alignItems: 'center',
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    rowGap: 30,
  },
  Button: {
    backgroundColor: '#EF8B49',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    width: '30%',
    height: 40,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  buttonText: {
    fontSize: 20,
    color: '#FFF',
  },
});
